### ISSUE TITLE
Link seems to be down. Can add the tutorial to the repo or post a new link?

### ISSUE THREAD

**Issue by 01GOD** [johndatserakis/RecordPlayer#1]
Hi

Looks like a cool project. Link to tutorial seems to be down. Can add the tutorial to the repo or post a new link?

Thanks in advance!

**Comment by johndatserakis** [comment]
Hey there, thanks for checking it out. Yup, it seems like the link had broken when I moved over my blog. Here's the new link: https://blog.johndatserakis.com/how-to-emulate-a-record-player-in-sprite-kit-using-swift-and-xcode/.

I do appreciate your interest in this. I will just warn you this was written a while ago and Swift has evolved a lot since then. I wonder if the code even runs anymore.

Regardless - thanks so much for the heads up!

**Comment by 01GOD** [comment]
Oh thanks! Yes, want to make something like a certain app that pairs with a
bluetooth crossfader, but make it possible to do turntablist things without
a hw crossfader.

Basically the app that pairs with a bluetooth fader is  a nice app, but
doesn't have a horizontal fader. So it's not easy to do standard
turntablist things.

Using capacitive gloves it actually is possible to move the platter in app
nicely, so want to see if a virtual fader will be enough. Maybe make a hw
fader using a capacitive pen also.

Nice for it to be possible to do turntablist sessions on only an ipad.

Was working on getting a circular waveform display to function also.

By the way, sadly xcode 12 said xcode 10 is necessary to migrate using that
migration tool. Tried to do it manually quick, but was reminded of what a
disaster swift was for years.

Maybe have another go at it sometime, but if ever up for it, welcome to
post a version compatible with swift 5.

Thanks again!

**Comment by johndatserakis** [comment]
Thank you - good luck - sounds interesting!
